name: day_planner
description: Simple meal reminder app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  timezone: ^0.9.4
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/menus/
    - assets/recipes/
    - assets/drinks/
    - assets/snacks/
    - assets/breakfast/
    - assets/lunch/
    - assets/dinner/Fancy/
    - assets/dinner/Taco/